CC      := g++
CFLAGS  := -std=c++11 -g
LIBS    := -lSDL2main -lSDL2

TITLE   := twodi
VERSION := 0.1.0
NUMBER  := $(shell ./script/build-id.sh)
COMMIT  := $(shell git rev-parse --short HEAD)
BRANCH  := $(shell git rev-parse --abbrev-ref HEAD)
DATE    := $(shell date +"%Y-%m-%d %H:%M:%S")

BINDIR  := bin
SRCDIR  := src
INCDIR  := include
LIBDIR  := lib
OBJDIR  := obj
RESDIR  := resource

SOURCES := $(shell find $(SRCDIR) -type f -name *.cpp)
OBJECTS := $(patsubst $(SRCDIR)/%,$(OBJDIR)/%,$(SOURCES:.cpp=.o))

.PHONY: all clean init generate build

all: init generate build

clean:
	@rm -rf $(BINDIR)
	@rm -rf $(OBJDIR)

init:
	@mkdir -p $(BINDIR)
	@mkdir -p $(OBJDIR)
	@echo "// Autogenerated header containing build information" > $(INCDIR)/Build.hpp
	@echo "#define BUILD_TITLE   \"$(TITLE)\""   >> $(INCDIR)/Build.hpp
	@echo "#define BUILD_VERSION \"$(VERSION)\"" >> $(INCDIR)/Build.hpp
	@echo "#define BUILD_NUMBER  \"$(NUMBER)\""  >> $(INCDIR)/Build.hpp
	@echo "#define BUILD_COMMIT  \"$(COMMIT)\""  >> $(INCDIR)/Build.hpp
	@echo "#define BUILD_BRANCH  \"$(BRANCH)\""  >> $(INCDIR)/Build.hpp
	@echo "#define BUILD_DATE    \"$(DATE)\""    >> $(INCDIR)/Build.hpp

generate:
	@cp $(RESDIR)/* $(BINDIR)
	@echo "$(VERSION) ($(COMMIT))" > $(BINDIR)/version.txt

build: $(BINDIR)/$(TITLE)

$(BINDIR)/$(TITLE): $(OBJECTS)
	@$(CC) -L $(LIBDIR) -o $(BINDIR)/$(TITLE) $^ $(LIBS)

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	@$(CC) $(CFLAGS) -I $(INCDIR) -c -o $@ $<
	@echo "CC    $@"
